# Generated by Django 3.2.8 on 2021-10-14 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='helplines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('state', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('orgtype', models.CharField(max_length=80)),
                ('ophrs', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('cost', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='issues',
            fields=[
                ('issue', models.CharField(max_length=80, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('detail', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('frel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.helplines')),
            ],
        ),
        migrations.CreateModel(
            name='avail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helpline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.helplines')),
                ('iss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.issues')),
            ],
        ),
    ]
