# Generated by Django 3.2.8 on 2021-10-15 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helplines',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='helplines',
            name='state',
            field=models.CharField(max_length=80),
        ),
    ]
