# Generated by Django 3.2.8 on 2021-11-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211015_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helplines',
            name='number',
            field=models.TextField(),
        ),
    ]
