# Generated by Django 3.2.8 on 2021-11-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_verify_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='verify',
            name='VerificationStatus',
            field=models.BooleanField(default=False),
        ),
    ]
