# Generated by Django 3.2.8 on 2021-11-08 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_assignhelpline_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='helplines',
            name='orgname',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
    ]
